/* Copyright (c) 2024 No Tomorrow Games. All rights reserved. */

#include <scene/ecs/EntityTag.hpp>
#include <scene/ecs/ComponentInterface.hpp>

namespace hyperion {

HYP_REGISTER_ENTITY_TAG(NONE, false);

HYP_REGISTER_ENTITY_TAG(STATIC, true);
HYP_REGISTER_ENTITY_TAG(DYNAMIC, true);
HYP_REGISTER_ENTITY_TAG(LIGHT, true);
HYP_REGISTER_ENTITY_TAG(CAMERA_PRIMARY, true);
HYP_REGISTER_ENTITY_TAG(LIGHTMAP_ELEMENT, true);

HYP_REGISTER_ENTITY_TAG(RECEIVES_UPDATE, false);

HYP_REGISTER_ENTITY_TAG(EDITOR_FOCUSED, false);

HYP_REGISTER_ENTITY_TAG(UI_OBJECT_VISIBLE, false);

HYP_REGISTER_ENTITY_TAG(UPDATE_AABB, false);
HYP_REGISTER_ENTITY_TAG(UPDATE_BVH, false);
HYP_REGISTER_ENTITY_TAG(UPDATE_BLAS, false);
HYP_REGISTER_ENTITY_TAG(UPDATE_RENDER_PROXY, false);
HYP_REGISTER_ENTITY_TAG(UPDATE_VISIBILITY_STATE, false);
HYP_REGISTER_ENTITY_TAG(UPDATE_LIGHT_TRANSFORM, false);
HYP_REGISTER_ENTITY_TAG(UPDATE_CAMERA_TRANSFORM, false);
HYP_REGISTER_ENTITY_TAG(UPDATE_ENV_GRID_TRANSFORM, false);
HYP_REGISTER_ENTITY_TAG(UPDATE_ENV_PROBE_TRANSFORM, false);

HYP_REGISTER_ENTITY_TAG(TYPE_ID, false);

} // namespace hyperion