/* Copyright (c) 2024 No Tomorrow Games. All rights reserved. */

#include <scene/ecs/EntityTag.hpp>
#include <scene/ecs/ComponentInterface.hpp>

namespace hyperion {

HYP_REGISTER_ENTITY_TAG(NONE);
HYP_REGISTER_ENTITY_TAG(STATIC);
HYP_REGISTER_ENTITY_TAG(DYNAMIC);
HYP_REGISTER_ENTITY_TAG(LIGHT);
HYP_REGISTER_ENTITY_TAG(UI);
HYP_REGISTER_ENTITY_TAG(UI_OBJECT_VISIBLE);
HYP_REGISTER_ENTITY_TAG(UPDATE_AABB);
HYP_REGISTER_ENTITY_TAG(UPDATE_BVH);
HYP_REGISTER_ENTITY_TAG(UPDATE_RENDER_PROXY);
HYP_REGISTER_ENTITY_TAG(UPDATE_VISIBILITY_STATE);

} // namespace hyperion