#ifndef LIGHT_FIELD_SHARED_GLSL
#define LIGHT_FIELD_SHARED_GLSL

#include "../include/Octahedron.glsl"

#define PROBE_SIDE_LENGTH 16
#define PROBE_BORDER_LENGTH 2
#define PROBE_SIDE_LENGTH_BORDER (PROBE_SIDE_LENGTH + PROBE_BORDER_LENGTH)

#endif